### ISSUE TITLE
Can not install pybluez with pip3

### ISSUE THREAD

**Issue by gamefriends** [pybluez/pybluez#136] opened 2016-08-06 06:01 UTC
The pyobjc is already.
Then
`sudo pip3 install pybluez`

get error:

`    creating build/temp.macosx-10.11-x86_64-3.5/osx
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/System/Library/Frameworks/IOBluetooth.framework/Headers -I/System/Library/Frameworks/CoreFoundation.framework/Headers -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c osx/_osxbt.c -o build/temp.macosx-10.11-x86_64-3.5/osx/_osxbt.o
    osx/_osxbt.c:676:5: error: unknown type name 'IOBluetoothDeviceInquiryRef'; did you mean 'IOBluetoothDeviceRef'?
        IOBluetoothDeviceInquiryRef inquiry;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
        IOBluetoothDeviceRef
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/IOBluetooth.framework/Headers/IOBluetoothUserLib.h:34:47: note: 'IOBluetoothDeviceRef' declared here
    typedef struct OpaqueIOBluetoothObjectRef \*                     IOBluetoothDeviceRef;
                                                                    ^
    osx/_osxbt.c:688:17: error: unknown type name 'IOBluetoothDeviceInquiryRef'; did you mean 'IOBluetoothDeviceRef'?
                    IOBluetoothDeviceInquiryRef inquiryRef,
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                    IOBluetoothDeviceRef
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/IOBluetooth.framework/Headers/IOBluetoothUserLib.h:34:47: note: 'IOBluetoothDeviceRef' declared here
    typedef struct OpaqueIOBluetoothObjectRef \*                     IOBluetoothDeviceRef;
                                                                    ^
    osx/_osxbt.c:703:19: warning: implicit declaration of function 'IOBluetoothDeviceInquiryCreateWithCallbackRefCon' is invalid in C99 [-Wimplicit-function-declaration]
        dd->inquiry = IOBluetoothDeviceInquiryCreateWithCallbackRefCon (&dd);
                      ^
    osx/_osxbt.c:703:17: warning: incompatible integer to pointer conversion assigning to 'IOBluetoothDeviceRef' (aka 'struct OpaqueIOBluetoothObjectRef *') from 'int' [-Wint-conversion]
        dd->inquiry = IOBluetoothDeviceInquiryCreateWithCallbackRefCon (&dd);
                    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    osx/_osxbt.c:705:5: warning: implicit declaration of function 'IOBluetoothDeviceInquirySetCompleteCallback' is invalid in C99 [-Wimplicit-function-declaration]
        IOBluetoothDeviceInquirySetCompleteCallback (dd->inquiry,
        ^
    osx/_osxbt.c:717:5: warning: implicit declaration of function 'IOBluetoothDeviceInquiryStart' is invalid in C99 [-Wimplicit-function-declaration]
        IOBluetoothDeviceInquiryStart (dd->inquiry);
        ^
    osx/_osxbt.c:721:5: warning: implicit declaration of function 'IOBluetoothDeviceInquiryDelete' is invalid in C99 [-Wimplicit-function-declaration]
        IOBluetoothDeviceInquiryDelete (dd->inquiry);
        ^
    osx/_osxbt.c:774:9: warning: implicit declaration of function 'Py_InitModule3' is invalid in C99 [-Wimplicit-function-declaration]
        m = Py_InitModule3("_osxbt", osxbt_methods, osxbt_doc);
            ^
    osx/_osxbt.c:774:7: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
        m = Py_InitModule3("_osxbt", osxbt_methods, osxbt_doc);
          ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    7 warnings and 2 errors generated.
    error: command 'clang' failed with exit status 1

```
----------------------------------------
```

Command "/usr/local/opt/python3/bin/python3.5 -u -c "import setuptools, tokenize;**file**='/private/tmp/pip-build-xh_px9kv/PyBluez/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-fuzvveos-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-xh_px9kv/PyBluez/`

How to fix it?

**Comment by karulis** [comment] 2016-08-25 21:19
this is duplicate of #133

**Closed as completed by karulis** 2016-08-25 21:19 UTC
Labels: duplicate
