### ISSUE TITLE
cant install pybluez

### ISSUE THREAD

**Issue by nickyuxing** [pybluez/pybluez#282] opened 2019-11-18 09:58 UTC
## System

 - **Operating System:*Win10*
 - **Hardware:*external Bluetooth adaptor* (e.g., Raspberry Pi, external Bluetooth adaptor, etc.)
 - **Python Version:*3.8*
 - **PyBluez Version:*0.22*

## Issue
C:\Users\Nick>call pip install pybluez
Collecting pybluez
  Using cached https://files.pythonhosted.org/packages/c1/98/3149481d508bee174335be6725880f00d297afebe75c15e917af8f6fe169/PyBluez-0.22.zip
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Nick\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Nick\\AppData\\Local\\Temp\\pip-install-0cu2jr0m\\pybluez\\setup.py'"'"'; __file__='"'"'C:\\Users\\Nick\\AppData\\Local\\Temp\\pip-install-0cu2jr0m\\pybluez\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Nick\AppData\Local\Temp\pip-install-0cu2jr0m\pybluez\pip-egg-info'
         cwd: C:\Users\Nick\AppData\Local\Temp\pip-install-0cu2jr0m\pybluez\
    Complete output (1 lines):
    Could not find the Windows Platform SDK
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by rgov** [comment] 2019-11-18 16:21
Dupe of #180

**Closed as completed by rgov** 2019-11-18 16:21 UTC
