### ISSUE TITLE
AttributeError: module 'bluetooth._msbt' has no attribute 'initwinsock'

### ISSUE THREAD

**Issue by ShadeOfOmuro** [pybluez/pybluez#385] opened 2021-01-14 15:50 UTC
- Win10 20H2
 - 3.8.7
 - 0.30

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\mynscenv\AppData\Local\Programs\Python\Python38\lib\site-packages\pybluez-0.30-py3.8-win-amd64.egg\bluetooth\__init__.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\mynscenv\AppData\Local\Programs\Python\Python38\lib\site-packages\pybluez-0.30-py3.8-win-amd64.egg\bluetooth\msbt.py", line 4, in <module>
AttributeError: module 'bluetooth._msbt' has no attribute 'initwinsock'

**Comment by cheriimoya** [comment] 2021-01-19 13:33
isn't this a duplicate of #369 ?

**Closed as completed** 2021-03-19 23:23 UTC
Labels: wontfix
